trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.6.0'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

jobs:
- job: TerraformDeploy
  displayName: 'Terraform Deploy'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  steps:
  - script: |
      wget https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip
      unzip terraform_$(terraformVersion)_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform version
    displayName: 'Install Terraform'
  
  - script: |
      terraform init
    displayName: 'Terraform Init'
    workingDirectory: $(workingDirectory)
  
  - script: |
      terraform plan
    displayName: 'Terraform Plan'
    workingDirectory: $(workingDirectory)
    env:
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_TENANT_ID: $(ARM_TENANT_ID)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
  
  - script: |
      terraform apply -auto-approve
    displayName: 'Terraform Apply'
    workingDirectory: $(workingDirectory)
    env:
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_TENANT_ID: $(ARM_TENANT_ID)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
